api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    path('likes/analytics/<str:from_date>/<str:to_date>/<str:api_key>', views.get_reaction_statistic, name='get_likes'),
]

django_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('social_network.urls')),
]

social_network/urls.py
from django.urls import path

from social_network import views

app_name = 'social_network'

urlpatterns = [
    # Login
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/logout/', views.UserLogoutView.as_view(), name='logout'),
    # Registration
    path('accounts/register/activate/<str:sign>/', views.user_activate, name='register_activate'),
    path('accounts/register/done/', views.RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    # Add and edit post
    path('accounts/profile/post_add/', views.profile_post_add, name='profile_post_add'),
    path('accounts/profile/post_edit/<int:pk>/', views.profile_post_change, name='profile_post_edit'),
    # Api token
    path('accounts/profile/personal_token/', views.api_token, name='profile_api_token'),

    path('accounts/profile/', views.profile_posts, name='profile'),
    # Post reaction
    path('reaction/<int:pk>', views.handle_reaction, name='handle_reaction'),
    path('', views.index, name='index'),

]

social_network/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
from social_network.utilities import get_timestamp_path


class PostUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Is this account activated?')
    date_last_request = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Last request to server')
    api_token = models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='Account api token')

    class Meta(AbstractUser.Meta):
        pass


class Post(models.Model):
    title = models.CharField(max_length=40,
                             verbose_name='Title')
    content = models.TextField(verbose_name='Content')

    image = models.ImageField(blank=True, upload_to=get_timestamp_path,
                              verbose_name='Image', null=True)

    is_active = models.BooleanField(default=True, db_index=True,
                                    verbose_name='Is post active')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Post created at')
    author = models.ForeignKey(PostUser, on_delete=models.CASCADE,
                               verbose_name='Author')

    def like_count(self):
        return self.likereaction_set.all().filter(reaction='like').count()

    def unlike_count(self):
        return self.likereaction_set.all().filter(reaction='unlike').count()

    def __str__(self):
        return "\"{}\" by {}".format(self.title, self.author)


class LikeReaction(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Like and unlike')
    author = models.ForeignKey(PostUser, on_delete=models.CASCADE,
                               verbose_name='Who (un)liked')
    reacted = models.DateTimeField(auto_now_add=True,
                                   db_index=True,
                                   verbose_name='Date of reaction')

    LIKE = 'like'
    UNLIKE = 'unlike'
    REACTION = [
        (LIKE, 'Like'),
        (UNLIKE, 'Not like')
    ]
    reaction = models.CharField(
        max_length=6,
        choices=REACTION,
        default=LIKE,
        verbose_name='user reaction'
    )

social_network/forms.py
from django import forms
from django.contrib.auth import password_validation
from .apps import user_registered
from django.core.exceptions import ValidationError

from .models import PostUser, Post


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Email address')
    password1 = forms.CharField(label='password',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())

    password2 = forms.CharField(label='repeat password',
                                widget=forms.PasswordInput,
                                help_text='enter password again')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        print(password1)
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        print(password1)
        print(password2)

        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('password not match',
                                                   code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        print('set pass')
        print(self.cleaned_data['password1'])
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
            # solved send activation letter
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = PostUser
        fields = ('username', 'password1', 'password2',
                  'first_name', 'last_name', 'email')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

social_network/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.crypto import get_random_string
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from social_network import forms
from social_network.forms import PostForm
from social_network.models import Post, PostUser, LikeReaction
from social_network.utilities import signer
from django.core.signing import BadSignature


def index(request):
    posts = Post.objects.filter(is_active=True)
    context = {'posts': posts}
    return render(request, 'main/index.html', context)


# region registration

class RegisterUserView(CreateView):
    model = PostUser
    template_name = 'registration/register_user.html'
    form_class = forms.RegisterUserForm
    success_url = reverse_lazy('social_network:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'


def generate_api_token():
    """token to access api info
    if token already exists, try again"""
    token = get_random_string(length=32)
    if PostUser.objects.filter(api_token=token):
        generate_api_token()
    else:
        return token


def user_activate(request, sign):
    # solved test this
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'errors/bad_signature.html')
    user = get_object_or_404(PostUser, username=username)
    if user.is_activated:
        template = 'registration/user_is_activated.html'
    else:
        template = 'registration/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.api_token = generate_api_token()
        print(f'token: {user.api_token}')
        user.save()
    return render(request, template)


# endregion

# region login
class UserLoginView(LoginView):
    template_name = 'login/login.html'


class UserLogoutView(LoginRequiredMixin, LogoutView):
    template_name = login = 'login/logout.html'


# endregion

# region post operations
@login_required
def profile_post_add(request):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        post = form.save()
        messages.add_message(request, messages.SUCCESS,
                             'Post added')
        return redirect('social_network:profile')
    else:
        form = PostForm(initial={'author': request.user.pk})
        context = {'form': form}
        return render(request, 'main/profile_post_add.html', context)


# solved image not changed, issue - multipart/data in html
@login_required
def profile_post_change(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Post edited')
            return redirect('social_network:profile')
    else:
        form = PostForm(instance=post)
        context = {'form': form}
        return render(request, 'main/profile_post_change.html', context)


@login_required
def profile_posts(request):
    """get post from current user"""
    posts = Post.objects.all().filter(author_id=request.user.pk)
    context = {'posts': posts}
    return render(request, 'main/profile.html', context)


# endregion

# region reaction handling
@login_required
def handle_reaction(request, pk):
    """handle like, or unlike action"""
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        # if post get user and reaction from request
        user_pk = request.user.pk
        print(request)
        reaction = request.POST.get('reaction')
        # if reaction - like
        if reaction == LikeReaction.LIKE:
            liked = post.likereaction_set.filter(author_id=user_pk).first()

            # if not reaction or user unliked it
            if not liked or liked.reaction == LikeReaction.UNLIKE:
                if not liked:
                    # if unliked - write new reaction
                    reaction = LikeReaction()
                else:
                    # set that reaction is like
                    reaction = liked
                    # add post and author to reaction
                reaction.post = post
                reaction.author = request.user
                reaction.reaction = reaction.LIKE
                # commit
                reaction.save()
        # if reaction unlike analog to like
        elif reaction == LikeReaction.UNLIKE:
            unliked = post.likereaction_set.filter(author_id=user_pk).first()
            if not unliked or unliked.reaction == LikeReaction.LIKE:
                if not unliked:
                    reaction = LikeReaction()
                else:
                    reaction = unliked
                reaction.post = post
                reaction.author = request.user
                reaction.reaction = reaction.UNLIKE
                reaction.save()
        # refresh page
        return redirect('social_network:index')


# endregion

# region api_token
@login_required
def api_token(request):
    return render(request, 'main/profile_api_key.html')

# endregion

social_network/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>social network</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
          crossorigin="anonymous">
    <title>Django Cards</title>
    <style>
        .arrow {
            display: inline-block;
            padding: 3px;
        }

        .arrow_color_green {
            border: solid green;
            border-width: 0 3px 3px 0;

        }
        .arrow_color_red {
            border: solid red;
            border-width: 0 3px 3px 0;
        }

        .right {
            transform: rotate(-45deg);
            -webkit-transform: rotate(-45deg);
        }

        .left {
            transform: rotate(135deg);
            -webkit-transform: rotate(135deg);
        }

        .up {
            transform: rotate(-135deg);
            -webkit-transform: rotate(-135deg);
        }

        .down {
            transform: rotate(45deg);
            -webkit-transform: rotate(45deg);
        }

        .hidden_text {
            font-size: 0;
            display: block;
            line-height: 0;
        }
    </style>
</head>
<body>
{% extends "layout/basic.html" %}
{% load static %}
{% block content %}
    {% if posts %}
        <h3 class="text-center">User posts</h3>
        <div style="display: flex; flex-direction: row; flex-wrap: wrap; align-content: center">
            {% if posts %}
                {% for post in posts %}
                    {% if post.is_active %}
                        <div class="card" style="width: 18rem;margin: 10px">
                            <h4>{{ post.author }}</h4>
                            {% if post.image %}
                                <img class="card-img-top" src="{% static post.image %}" alt="image">
                            {% else %}
                                <img class="card-img-top" src="{% static 'alt_image.jpg' %}" alt="alt">
                            {% endif %}
                            <div class="card-body">
                                <div style="display: flex; flex-direction: row">
                                    <h4 class="card-title">{{ post.title }}</h4>
                                    <div style="
                                            background: olivedrab;
                                            width: 20px;
                                            height: 20px;
                                            margin-left: 10px;
                                            border-radius: 50%;">
                                    </div>
                                </div>
                                <div>
                                    <p class="card-text">{{ post.content }}</p>
                                    <form method="post" action="{% url 'social_network:handle_reaction' pk=post.pk %}">
                                        {% csrf_token %}
                                        <input name="post_id" type="hidden" value="{{ post.id }}">
                                        <div class="container">
                                            <div class="container">
                                                <input type="submit" class="arrow up hidden_text arrow_color_green"
                                                       name="reaction"
                                                       value="like"><b>{{ post.like_count }}</b>
                                            </div>
                                            <div class="container">
                                                <input type="submit" name="reaction" value="unlike"
                                                       class="arrow down hidden_text arrow_color_red"><b>{{ post.unlike_count }}</b><br>
                                            </div>
                                        </div>

                                    </form>

                                    <p>{{ post.created_at.date }}</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <h4 class="text-center"></h4>
                </div>
            {% endif %}
    {% else %}
        <h3>Any posts yet</h3>
    {% endif %}
{% endblock %}
</body>
</html>

social_network/templates/main/profile.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% load static %}
{% block title %}User profile{% endblock %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous">
{% block content %}
    {% if user.username %}
        <p>Hello, {{ user.username }}!</p>
    {% else %}
        <p>Hello!</p>
    {% endif %}
    {% if posts %}
        <h3>Your posts</h3>
        <div style="display: flex; flex-direction: row; flex-wrap: wrap">
            {% if posts %}
                {% for post in posts %}
                    <li class="card" style="width: 18rem; margin: 10px">
                        {% url 'social_network:profile_post_edit' pk=post.pk as url %}
                        <div class="media-body">
                            <a href="{{ url }}{{ all }}">
                                {% if post.image %}
                                    <img class="card-img-top" src="{% static post.image %}" alt="image">
                                {% else %}
                                    <img class="card-img-top" src="{% static 'alt_image.jpg' %}" alt="alt">
                                {% endif %}
                            </a>
                        </div>
                        <div class="card-body">
                            <div>
                                <h4 class="card-title">{{ post.title }}</h4>
                                <p class="card-text">{{ post.content }}</p>
                            </div>
                            <br>
                            <div>
                                <p class>{{ post.created_at.date }}</p>
                            </div>
                            <div>
                                liked:
                                <b>{{ post.like_count }}</b>
                                unliked:
                                <b>{{ post.unlike_count }}</b><br>

                            </div>
                            <div>

                                <a class="btn btn-primary" href="{{ url }}{{ all }}">edit</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                </div>
            {% else %}
                <h4 class="text-center"></h4>
            {% endif %}
    {% else %}
        <h3>You don`t have any posts yet</h3>
    {% endif %}
{% endblock %}

social_network/templates/main/profile_api_key.html
{% extends "layout/basic.html" %}
{% block title %} Api token {% endblock %}
{% block content %}
    {% if user.api_token %}
        <h3>{{ user.username }},this is your personal api token</h3>
        <p><b><i>{{ user.api_token }}</i></b></p>
    {% else %}
        <h3>You don't have api token</h3>
    {% endif %}

{% endblock %}

social_network/templates/main/profile_post_add.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Post adding - User profile{% endblock %}
{% block content %}
    <h2>Post adding</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit="Add" %} {% endbuttons %}
    </form>
{% endblock %}

social_network/templates/main/profile_post_change.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Edit post{% endblock %}
{% block content %}
    <h2>Edit post {{ post.title }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="hidden" name="next" value="{{ next }}">
        {% buttons submit="Save" %} {% endbuttons %}
    </form>
{% endblock %}